services:
  krakend_ee:
    build:
      context: .
      args:
        - KRAKEND_BUILDER=2.13
        - KRAKEND_VERSION=2.13.0
    init: true
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:  
    image: "redis:7"
    ports:
      - "6379:6379"
