services:
  krakend_ee:
    image: krakend/krakend-ee:3.0.0-sc1458-alpha1
    init: true
    volumes:
      - ./config/krakend:/etc/krakend
      - ./LICENSE:/etc/krakend/LICENSE
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "krakend.json"]
  nginx:
    image: nginx:1.31.6
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/html:/usr/share/nginx/html
    ports:
      - "8085:8080"
    depends_on:
      - krakend_ee
