version: "3"
services:
  krakend:
    image: devopsfaith/krakend:watch
    volumes:
      - .:/etc/krakend
      - ./mime.types:/etc/mime.types
    ports:
      - "8080:8080"
    command: [ "run", "-dc", "krakend.json", "" ]
