version: "3"
services:
  fake_api:
    image: php:8-apache
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "8001:80"
  krakend:
    image: devopsfaith/krakend:2.0
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: ["run", "-c", "krakend.json", "-d"]
    ports:
      - "8080:8080"
    depends_on:
      - fake_api
